name: Build .NET Framework 4.8 WinApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Build Solution
      run: msbuild.exe Lab.sln /p:platform="Any CPU" /p:configuration="Release" 

    - name: Publish Build Artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: BuildArtifacts
        path: |
          **/bin/Release/
